
package com.poweruniverse.nim.plateform.wsclient.designer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DesignerWebserviceImpl", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DesignerWebserviceImpl {


    /**
     * 
     * @param pageUrl
     * @param pageDef
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.designer.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePageDef", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.SavePageDef")
    @ResponseWrapper(localName = "savePageDefResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.SavePageDefResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/savePageDefRequest", output = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/savePageDefResponse")
    public JsonMessageResult savePageDef(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl,
        @WebParam(name = "pageDef", targetNamespace = "")
        String pageDef);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.designer.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPageDef", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadPageDef")
    @ResponseWrapper(localName = "readPageDefResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadPageDefResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readPageDefRequest", output = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readPageDefResponse")
    public JsonMessageResult readPageDef(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param content
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.designer.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveFile", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.SaveFile")
    @ResponseWrapper(localName = "saveFileResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.SaveFileResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/saveFileRequest", output = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/saveFileResponse")
    public JsonMessageResult saveFile(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl,
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.designer.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readFile", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadFile")
    @ResponseWrapper(localName = "readFileResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadFileResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readFileRequest", output = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readFileResponse")
    public StringResult readFile(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.designer.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readCmpDef", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadCmpDef")
    @ResponseWrapper(localName = "readCmpDefResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.designer.ReadCmpDefResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readCmpDefRequest", output = "http://webservice.plateform.nim.poweruniverse.com/DesignerWebserviceImpl/readCmpDefResponse")
    public JsonMessageResult readCmpDef(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath);

}
