
package com.poweruniverse.nim.data.wsclient.verify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VerifyWebserviceImpl", targetNamespace = "http://webservice.data.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VerifyWebserviceImpl {


    /**
     * 
     * @param password
     * @param user
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.verify.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkLogin", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.CheckLogin")
    @ResponseWrapper(localName = "checkLoginResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.CheckLoginResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/checkLoginRequest", output = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/checkLoginResponse")
    public JsonMessageResult checkLogin(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param caoZuoDH
     * @param gongNengDH
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.verify.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasGNCZAuth", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.HasGNCZAuth")
    @ResponseWrapper(localName = "hasGNCZAuthResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.HasGNCZAuthResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/hasGNCZAuthRequest", output = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/hasGNCZAuthResponse")
    public JsonMessageResult hasGNCZAuth(
        @WebParam(name = "gongNengDH", targetNamespace = "")
        String gongNengDH,
        @WebParam(name = "caoZuoDH", targetNamespace = "")
        String caoZuoDH);

    /**
     * 
     * @param id
     * @param caoZuoDH
     * @param gongNengDH
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.verify.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasAuth", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.HasAuth")
    @ResponseWrapper(localName = "hasAuthResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.verify.HasAuthResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/hasAuthRequest", output = "http://webservice.data.nim.poweruniverse.com/VerifyWebserviceImpl/hasAuthResponse")
    public JsonMessageResult hasAuth(
        @WebParam(name = "gongNengDH", targetNamespace = "")
        String gongNengDH,
        @WebParam(name = "caoZuoDH", targetNamespace = "")
        String caoZuoDH,
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
