
package com.poweruniverse.nim.data.wsclient.data;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataWebserviceImplService", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-data/data?wsdl")
public class DataWebserviceImplService
    extends Service
{

    private final static URL DATAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DATAWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.data.nim.poweruniverse.com/", "DataWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-data/data?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DATAWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DataWebserviceImplService() {
        super(__getWsdlLocation(), DATAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DataWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DataWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, DATAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DataWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DataWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataWebserviceImpl
     */
    @WebEndpoint(name = "DataWebserviceImplPort")
    public DataWebserviceImpl getDataWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "DataWebserviceImplPort"), DataWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataWebserviceImpl
     */
    @WebEndpoint(name = "DataWebserviceImplPort")
    public DataWebserviceImpl getDataWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "DataWebserviceImplPort"), DataWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DATAWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DATAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
