
package com.poweruniverse.nim.plateform.wsclient.plugin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PluginWebserviceImpl", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PluginWebserviceImpl {


    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.plugin.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "html", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.Html")
    @ResponseWrapper(localName = "htmlResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.HtmlResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/htmlRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/htmlResponse")
    public JsonMessageResult html(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.plugin.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "js", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.Js")
    @ResponseWrapper(localName = "jsResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.JsResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/jsRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/jsResponse")
    public StringResult js(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.plugin.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "css", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.Css")
    @ResponseWrapper(localName = "cssResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.plugin.CssResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/cssRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PluginWebserviceImpl/cssResponse")
    public StringResult css(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

}
