
package com.poweruniverse.nim.plateform.wsclient.plugin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PluginWebserviceImplService", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-plateform/plugin?wsdl")
public class PluginWebserviceImplService
    extends Service
{

    private final static URL PLUGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLUGINWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PLUGINWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.plateform.nim.poweruniverse.com/", "PluginWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-plateform/plugin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLUGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PLUGINWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PluginWebserviceImplService() {
        super(__getWsdlLocation(), PLUGINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PluginWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLUGINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PluginWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, PLUGINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PluginWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLUGINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PluginWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PluginWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PluginWebserviceImpl
     */
    @WebEndpoint(name = "PluginWebserviceImplPort")
    public PluginWebserviceImpl getPluginWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.plateform.nim.poweruniverse.com/", "PluginWebserviceImplPort"), PluginWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PluginWebserviceImpl
     */
    @WebEndpoint(name = "PluginWebserviceImplPort")
    public PluginWebserviceImpl getPluginWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.plateform.nim.poweruniverse.com/", "PluginWebserviceImplPort"), PluginWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLUGINWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PLUGINWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PLUGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
