
package com.poweruniverse.nim.data.wsclient.analyse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnalyseWebserviceImpl", targetNamespace = "http://webservice.data.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnalyseWebserviceImpl {


    /**
     * 
     * @param cfgContent
     * @param params
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.analyse.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "analyse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.analyse.Analyse")
    @ResponseWrapper(localName = "analyseResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.analyse.AnalyseResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/AnalyseWebserviceImpl/analyseRequest", output = "http://webservice.data.nim.poweruniverse.com/AnalyseWebserviceImpl/analyseResponse")
    public StringResult analyse(
        @WebParam(name = "cfgContent", targetNamespace = "")
        String cfgContent,
        @WebParam(name = "params", targetNamespace = "")
        String params);

}
