
package com.poweruniverse.nim.data.wsclient.analyse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnalyseWebserviceImplService", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-data/analyse?wsdl")
public class AnalyseWebserviceImplService
    extends Service
{

    private final static URL ANALYSEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANALYSEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ANALYSEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.data.nim.poweruniverse.com/", "AnalyseWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-data/analyse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANALYSEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ANALYSEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AnalyseWebserviceImplService() {
        super(__getWsdlLocation(), ANALYSEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AnalyseWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANALYSEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AnalyseWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, ANALYSEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AnalyseWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANALYSEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AnalyseWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalyseWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnalyseWebserviceImpl
     */
    @WebEndpoint(name = "AnalyseWebserviceImplPort")
    public AnalyseWebserviceImpl getAnalyseWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "AnalyseWebserviceImplPort"), AnalyseWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnalyseWebserviceImpl
     */
    @WebEndpoint(name = "AnalyseWebserviceImplPort")
    public AnalyseWebserviceImpl getAnalyseWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "AnalyseWebserviceImplPort"), AnalyseWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANALYSEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ANALYSEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ANALYSEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
