
package com.poweruniverse.nim.plateform.wsclient.page;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PageWebserviceImpl", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PageWebserviceImpl {


    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.page.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "css", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.Css")
    @ResponseWrapper(localName = "cssResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.CssResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/cssRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/cssResponse")
    public StringResult css(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @param params
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.page.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "analyse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.Analyse")
    @ResponseWrapper(localName = "analyseResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.AnalyseResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/analyseRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/analyseResponse")
    public StringResult analyse(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl,
        @WebParam(name = "params", targetNamespace = "")
        String params);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.page.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orginal", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.Orginal")
    @ResponseWrapper(localName = "orginalResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.OrginalResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/orginalRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/orginalResponse")
    public JsonMessageResult orginal(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.page.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "html", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.Html")
    @ResponseWrapper(localName = "htmlResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.HtmlResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/htmlRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/htmlResponse")
    public JsonMessageResult html(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

    /**
     * 
     * @param pageUrl
     * @param contextPath
     * @return
     *     returns com.poweruniverse.nim.plateform.wsclient.page.StringResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "js", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.Js")
    @ResponseWrapper(localName = "jsResponse", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", className = "com.poweruniverse.nim.plateform.wsclient.page.JsResponse")
    @Action(input = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/jsRequest", output = "http://webservice.plateform.nim.poweruniverse.com/PageWebserviceImpl/jsResponse")
    public StringResult js(
        @WebParam(name = "contextPath", targetNamespace = "")
        String contextPath,
        @WebParam(name = "pageUrl", targetNamespace = "")
        String pageUrl);

}
