
package com.poweruniverse.nim.plateform.wsclient.page;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PageWebserviceImplService", targetNamespace = "http://webservice.plateform.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-plateform/page?wsdl")
public class PageWebserviceImplService
    extends Service
{

    private final static URL PAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PAGEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.plateform.nim.poweruniverse.com/", "PageWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-plateform/page?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PAGEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PageWebserviceImplService() {
        super(__getWsdlLocation(), PAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PageWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PageWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, PAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PageWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PageWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PageWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PageWebserviceImpl
     */
    @WebEndpoint(name = "PageWebserviceImplPort")
    public PageWebserviceImpl getPageWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.plateform.nim.poweruniverse.com/", "PageWebserviceImplPort"), PageWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PageWebserviceImpl
     */
    @WebEndpoint(name = "PageWebserviceImplPort")
    public PageWebserviceImpl getPageWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.plateform.nim.poweruniverse.com/", "PageWebserviceImplPort"), PageWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
