
package com.poweruniverse.nim.data.wsclient.task;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaskWebserviceImpl", targetNamespace = "http://webservice.data.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaskWebserviceImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.task.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doTask", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.task.DoTask")
    @ResponseWrapper(localName = "doTaskResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.task.DoTaskResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/TaskWebserviceImpl/doTaskRequest", output = "http://webservice.data.nim.poweruniverse.com/TaskWebserviceImpl/doTaskResponse")
    public JsonMessageResult doTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3);

    /**
     * 
     * @param objectId
     * @param caoZuoDH
     * @param gongNengDH
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.task.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.task.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.task.GetStatusResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/TaskWebserviceImpl/getStatusRequest", output = "http://webservice.data.nim.poweruniverse.com/TaskWebserviceImpl/getStatusResponse")
    public JsonMessageResult getStatus(
        @WebParam(name = "gongNengDH", targetNamespace = "")
        String gongNengDH,
        @WebParam(name = "caoZuoDH", targetNamespace = "")
        String caoZuoDH,
        @WebParam(name = "objectId", targetNamespace = "")
        Integer objectId);

}
