
package com.poweruniverse.nim.data.wsclient.task;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskWebserviceImplService", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-data/task?wsdl")
public class TaskWebserviceImplService
    extends Service
{

    private final static URL TASKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TASKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.data.nim.poweruniverse.com/", "TaskWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-data/task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TASKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TaskWebserviceImplService() {
        super(__getWsdlLocation(), TASKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TaskWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TaskWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, TASKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TaskWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TaskWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskWebserviceImpl
     */
    @WebEndpoint(name = "TaskWebserviceImplPort")
    public TaskWebserviceImpl getTaskWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "TaskWebserviceImplPort"), TaskWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskWebserviceImpl
     */
    @WebEndpoint(name = "TaskWebserviceImplPort")
    public TaskWebserviceImpl getTaskWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "TaskWebserviceImplPort"), TaskWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TASKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TASKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
