
package com.poweruniverse.nim.data.wsclient.file;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileWebserviceImplService", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", wsdlLocation = "http://127.0.0.1:1081/ws/nim-data/file?wsdl")
public class FileWebserviceImplService
    extends Service
{

    private final static URL FILEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FILEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.data.nim.poweruniverse.com/", "FileWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1081/ws/nim-data/file?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FILEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FileWebserviceImplService() {
        super(__getWsdlLocation(), FILEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FileWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FileWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, FILEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FileWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FileWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileWebserviceImpl
     */
    @WebEndpoint(name = "FileWebserviceImplPort")
    public FileWebserviceImpl getFileWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "FileWebserviceImplPort"), FileWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileWebserviceImpl
     */
    @WebEndpoint(name = "FileWebserviceImplPort")
    public FileWebserviceImpl getFileWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.data.nim.poweruniverse.com/", "FileWebserviceImplPort"), FileWebserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FILEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FILEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
