
package com.poweruniverse.nim.data.wsclient.file;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileWebserviceImpl", targetNamespace = "http://webservice.data.nim.poweruniverse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileWebserviceImpl {


    /**
     * 
     * @param fileId
     * @param fileHandler
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.file.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reUpload", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.ReUpload")
    @ResponseWrapper(localName = "reUploadResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.ReUploadResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/reUploadRequest", output = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/reUploadResponse")
    public JsonMessageResult reUpload(
        @WebParam(name = "fileId", targetNamespace = "")
        String fileId,
        @WebParam(name = "fileHandler", targetNamespace = "")
        DataHandler fileHandler);

    /**
     * 
     * @param fileId
     * @return
     *     returns javax.activation.DataHandler
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.DownloadResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/downloadRequest", output = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/downloadResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/download/Fault/Exception")
    })
    public DataHandler download(
        @WebParam(name = "fileId", targetNamespace = "")
        Integer fileId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param fuJianLXDH
     * @param fileHandler
     * @param fileName
     * @return
     *     returns com.poweruniverse.nim.data.wsclient.file.JsonMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://webservice.data.nim.poweruniverse.com/", className = "com.poweruniverse.nim.data.wsclient.file.UploadResponse")
    @Action(input = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/uploadRequest", output = "http://webservice.data.nim.poweruniverse.com/FileWebserviceImpl/uploadResponse")
    public JsonMessageResult upload(
        @WebParam(name = "fuJianLXDH", targetNamespace = "")
        String fuJianLXDH,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "fileHandler", targetNamespace = "")
        DataHandler fileHandler);

}
